### ISSUE TITLE
Reset expirey for existing key

### ISSUE THREAD

**Issue by bararchy** [samueleaton/cache-hash#2]
Can't figure if this feature is missing or I didn't find it :)

**Comment by samueleaton** [comment]
I was debating adding this or not.

Doing `my_hash.set("my_key", my_hash.get("my_key"))` will work of course but its not really clean.

I think I'll add that feature. What do you propose? I was thinking `.refresh(key)` would reset the expiration to `Time.now` and it would only work if the key has not yet expired. Once a key is expired, it gone.

**Comment by bararchy** [comment]
Yeha , sounds good , for still valid keys , .refresh(:key)

**Comment by samueleaton** [comment]
done https://github.com/samueleaton/cache-hash/pull/3
